export type Lang = 'uz' | 'ru' | 'en';

export const languages = {
  uz: {
    welcome: '👋 Assalomu alaykum! <b>LegalUZ</b> botiga xush kelibsiz!\n\n⚖️ O\'zbekistondagi yuristlar va mijozlarni birlashtiruvchi professional yuridik platforma.',
    selectLanguage: '🌐 Tilni tanlang:',
    subscribeRequired: `📢 Botdan foydalanish uchun quyidagi kanallarga obuna bo'ling:\n\n1️⃣ @LegalUz_Y_u\n2️⃣ @LegalUz_M_u\n3️⃣ @Yurist_ND\n\n📁 Papka: https://t.me/addlist/LAV6HuGmEOJlOGVi`,
    checkSubscription: '✅ Obunani tekshirish',
    notSubscribed: '❌ Siz hali barcha kanallarga obuna bo\'lmadingiz!\n\nIltimos, barcha kanallarga obuna bo\'lib qaytadan tekshiring.',
    subscribed: '✅ Obuna tasdiqlandi! Xush kelibsiz!',
    selectSection: '📋 Bo\'limni tanlang:',
    btnAds: '📢 Elon joylash',
    btnAI: '🤖 AI Konsultatsiya',
    btnDocs: '📁 Hujjatlar',
    btnAdmin: '💬 Biz bilan bog\'lanish',
    btnLegalConsult: '⚖️ Huquqiy tushuntirish',
    btnDocCreate: '✍️ Hujjat tuzib berish',
    btnSupport: '📞 Support',
    btnBack: '🏠 Asosiy menyu',
    btnCancel: '❌ Bekor qilish',
    btnMainMenu: '🏠 Asosiy menyu',
    selectAdType: '📢 Elon turini tanlang:',
    btnClientAd: '👤 Murojaatchi sifatida',
    btnSpecialistAd: '👨‍⚖️ Mutaxassis sifatida',
    clientAdField: '📌 Qaysi soha bo\'yicha yurdiuik yordam kerak?\n\n(Masalan: mehnat huquqi, mulk, oila, biznes...)',
    clientAdRegion: '📍 Qaysi viloyat yoki shahardansiz?',
    clientAdDescription: '📝 Muammongizni batafsil yozing:',
    clientAdContact: '📞 Aloqa ma\'lumotingizni kiriting (telefon raqam yoki Telegram username):',
    clientAdPosted: '✅ E\'loningiz muvaffaqiyatli joylashtirildi!\n\nMutaxassislar siz bilan bog\'lanadi.',
    specialistAdField: '⚖️ Qaysi soha bo\'yicha mutaxasssissiz?\n\n(Masalan: jinoyat, fuqarolik, mehnat, oila, biznes huquqi...)',
    specialistAdRegion: '📍 Qaysi viloyat yoki shaharda faoliyat yuritasiz?',
    specialistAdExperience: '📅 Necha yillik tajribangiz bor?',
    specialistAdPrice: '💰 Konsultatsiya narxi (so\'mda yoki "Kelishiladi"):',
    specialistAdDescription: '📝 O\'zingiz haqingizda qisqacha ma\'lumot bering:',
    specialistAdContact: '📞 Aloqa ma\'lumotingizni kiriting (telefon raqam yoki Telegram username):',
    specialistAdPosted: '✅ E\'loningiz muvaffaqiyatli joylashtirildi!',
    aiWelcome: '🤖 <b>AI Konsultatsiya</b>\n\nO\'zbekiston qonunchiligiga oid savolingizni yozing. Yurist assistant sizga yordam beradi.\n\n❓ Savolingizni kiriting:',
    aiTyping: '⏳ Javob tayyorlanmoqda...',
    aiError: '❌ Xatolik yuz berdi. Iltimos qayta urinib ko\'ring.',
    docsWelcome: '📁 <b>Hujjatlar</b>\n\nQuyidagi bo\'limlardan birini tanlang:',
    btnDocSamples: '📄 Hujjat namunalari',
    btnDocTemplates: '📋 Shablonlar',
    docSampleCategories: '📄 Hujjat namunalari bo\'limini tanlang:',
    btnSudHujjatlari: '⚖️ Sud hujjatlari',
    btnArizalar: '📝 Arizalar',
    btnShartnomaMisollari: '📃 Shartnoma misollari',
    btnBoshqaHujjatlar: '📂 Boshqa hujjatlar',
    templateCategories: '📋 Shablonlar bo\'limini tanlang:',
    btnShartnomalar: '📑 Shartnomalar',
    btnDavoArizalari: '⚖️ Davo arizalari',
    btnKorporativHujjatlar: '🏢 Korporativ hujjatlar',
    btnTemplateBoshqa: '📂 Boshqa shablonlar',
    docsEmpty: '📭 Bu bo\'limda hozircha hujjatlar mavjud emas.',
    docPaidMsg: (name: string, price: number, card: string, cardOwner: string) =>
      `💰 <b>${name}</b> hujjati pullik.\n\nNarx: <b>${price.toLocaleString()} so'm</b>\n\n📲 To'lov uchun:\n👤 ${cardOwner}\n💳 ${card}\n\nTo'lovni amalga oshirib, screenshot yuboring.`,
    docPaymentReceived: '✅ To\'lovingiz qabul qilindi! Hujjat tayyorlanmoqda...',
    adminWelcome: '💬 <b>Biz bilan bog\'lanish</b>\n\nXabaringizni yozing, tez orada javob beramiz:',
    adminSent: '✅ Xabaringiz adminga yuborildi. Tez orada javob beramiz!',
    adminMsgSend: '📨 Xabar yuborish',
    legalConsultWelcome: `⚖️ <b>Huquqiy tushuntirish</b>\n\nBu bo'limda yuristlarimiz sizning huquqiy muammolaringizni tahlil qilib, tushunarli izoh beradilar.\n\n💡 Xizmat hajmiga qarab <b>pullik yoki bepul</b> bo'lishi mumkin.\n\nMuammoingizni batafsil yozing:`,
    legalConsultSent: '✅ Murojaatingiz qabul qilindi! Yuristlar ko\'rib chiqib, tez orada javob beradilar.',
    legalConsultWaiting: '⏳ Murojaatingiz ko\'rib chiqilmoqda, kuting...',
    docCreateWelcome: `✍️ <b>Hujjat tuzib berish</b>\n\nBu bo'limda yuristlarimiz siz uchun kerakli yuridik hujjatni tuzib beradilar.\n\n💡 Xizmat hajmiga qarab <b>pullik yoki bepul</b> bo'lishi mumkin.\n\nQanday hujjat kerakligini yozing (masalan: ish shartnomasi, ijara shartnomasi, da'vo arizasi...):`,
    docCreateSent: '✅ So\'rovingiz qabul qilindi! Yuristlar ko\'rib chiqib, tez orada javob beradilar.',
    supportWelcome: '📞 <b>Support</b>\n\nSavolingiz yoki muammoingizni yozing:',
    supportSent: '✅ Xabaringiz support xizmatiga yuborildi!',
    requestAccepted: (account: string, comment: string) =>
      `✅ <b>Murojaatingiz qabul qilindi!</b>\n\n💬 Izoh: ${comment}\n\n👤 Mutaxassis: ${account}\n\nUsha akkaunt orqali bog'laning.`,
    requestRejected: (reason: string) =>
      `❌ <b>Afsuski, murojaatingiz rad etildi.</b>\n\n📝 Sabab: ${reason}\n\nUzr so'raymiz. Boshqa savolingiz bo'lsa, qaytadan murojaat qiling.`,
    cancel: '❌ Bekor qilindi. Asosiy menyuga qaytdingiz.',
    adminPanel: '👨‍💼 <b>Admin Panel</b>\n\nBo\'limni tanlang:',
    btnAdminMonitor: '📊 Monitoring',
    btnAdminBroadcast: '📢 Ommaviy post',
    btnAdminAddDoc: '📄 Hujjat qo\'shish',
    btnAdminPayment: '💳 To\'lov kartasi',
    adminBroadcastPrompt: '📢 Barcha foydalanuvchilarga yuboriladigan xabarni kiriting:',
    adminBroadcastDone: (count: number) => `✅ Xabar ${count} ta foydalanuvchiga yuborildi.`,
    adminAddDocType: '📂 Hujjat turini tanlang:',
    btnSampleDoc: '📄 Hujjat namunasi',
    btnTemplateDoc: '📋 Shablon',
    adminAddDocCategory: '📂 Kategoriyani tanlang:',
    adminAddDocFile: '📎 Hujjatni yuboring (fayl yoki rasm):',
    adminAddDocName: '✏️ Hujjatga nom bering (o\'zbek tilida):',
    adminAddDocNameRu: '✏️ Hujjat nomini rus tilida kiriting:',
    adminAddDocNameEn: '✏️ Hujjat nomini ingliz tilida kiriting:',
    adminAddDocCode: '🔑 Hujjat kodini kiriting (2 bosh harf + 3 raqam, masalan: HA001):',
    adminAddDocPrice: '💰 Narx belgilang (0 = bepul, boshqa son = pullik, so\'mda):',
    adminDocAdded: '✅ Hujjat muvaffaqiyatli qo\'shildi!',
    adminPaymentMenu: '💳 To\'lov kartasi boshqaruvi:',
    btnAddCard: '➕ Karta qo\'shish',
    btnRemoveCard: '🗑️ Karta o\'chirish',
    btnViewCards: '👁️ Kartalar ro\'yxati',
    adminCardOwner: '👤 Karta egasining ismini kiriting:',
    adminCardNumber: '💳 Karta raqamini yoki linkini kiriting:',
    adminCardAdded: '✅ Karta muvaffaqiyatli qo\'shildi!',
    adminCardRemoved: '✅ Karta o\'chirildi.',
    noCards: '💳 Hozircha karta qo\'shilmagan.',
    monitoringInfo: (users: number, today: number, ads: number) =>
      `📊 <b>Monitoring</b>\n\n👥 Jami foydalanuvchilar: ${users}\n📅 Bugun qo\'shilgan: ${today}\n📢 Jami e'lonlar: ${ads}`,
  },

  ru: {
    welcome: '👋 Добро пожаловать в <b>LegalUZ</b>!\n\n⚖️ Профессиональная юридическая платформа, объединяющая юристов и клиентов Узбекистана.',
    selectLanguage: '🌐 Выберите язык:',
    subscribeRequired: `📢 Для использования бота подпишитесь на каналы:\n\n1️⃣ @LegalUz_Y_u\n2️⃣ @LegalUz_M_u\n3️⃣ @Yurist_ND\n\n📁 Папка: https://t.me/addlist/LAV6HuGmEOJlOGVi`,
    checkSubscription: '✅ Проверить подписку',
    notSubscribed: '❌ Вы ещё не подписаны на все каналы!\n\nПожалуйста, подпишитесь и проверьте снова.',
    subscribed: '✅ Подписка подтверждена! Добро пожаловать!',
    selectSection: '📋 Выберите раздел:',
    btnAds: '📢 Разместить объявление',
    btnAI: '🤖 AI Консультация',
    btnDocs: '📁 Документы',
    btnAdmin: '💬 Связаться с нами',
    btnLegalConsult: '⚖️ Юридическое разъяснение',
    btnDocCreate: '✍️ Составить документ',
    btnSupport: '📞 Поддержка',
    btnBack: '🏠 Главное меню',
    btnCancel: '❌ Отмена',
    btnMainMenu: '🏠 Главное меню',
    selectAdType: '📢 Выберите тип объявления:',
    btnClientAd: '👤 Как клиент',
    btnSpecialistAd: '👨‍⚖️ Как специалист',
    clientAdField: '📌 В какой области нужна юридическая помощь?\n\n(Например: трудовое право, имущество, семья, бизнес...)',
    clientAdRegion: '📍 Из какого вы региона/города?',
    clientAdDescription: '📝 Опишите вашу проблему подробно:',
    clientAdContact: '📞 Введите контактные данные (телефон или Telegram username):',
    clientAdPosted: '✅ Ваше объявление успешно размещено!\n\nСпециалисты свяжутся с вами.',
    specialistAdField: '⚖️ В какой области вы специализируетесь?\n\n(Например: уголовное, гражданское, трудовое, семейное, бизнес право...)',
    specialistAdRegion: '📍 В каком регионе/городе вы работаете?',
    specialistAdExperience: '📅 Сколько лет опыта?',
    specialistAdPrice: '💰 Стоимость консультации (в сумах или "Договорная"):',
    specialistAdDescription: '📝 Краткая информация о себе:',
    specialistAdContact: '📞 Введите контактные данные (телефон или Telegram username):',
    specialistAdPosted: '✅ Ваше объявление успешно размещено!',
    aiWelcome: '🤖 <b>AI Консультация</b>\n\nЗадайте вопрос по законодательству Узбекистана. Юридический ассистент поможет вам.\n\n❓ Введите ваш вопрос:',
    aiTyping: '⏳ Подготовка ответа...',
    aiError: '❌ Произошла ошибка. Попробуйте снова.',
    docsWelcome: '📁 <b>Документы</b>\n\nВыберите раздел:',
    btnDocSamples: '📄 Образцы документов',
    btnDocTemplates: '📋 Шаблоны',
    docSampleCategories: '📄 Выберите категорию образцов:',
    btnSudHujjatlari: '⚖️ Судебные документы',
    btnArizalar: '📝 Заявления',
    btnShartnomaMisollari: '📃 Образцы договоров',
    btnBoshqaHujjatlar: '📂 Другие документы',
    templateCategories: '📋 Выберите категорию шаблонов:',
    btnShartnomalar: '📑 Договоры',
    btnDavoArizalari: '⚖️ Исковые заявления',
    btnKorporativHujjatlar: '🏢 Корпоративные документы',
    btnTemplateBoshqa: '📂 Другие шаблоны',
    docsEmpty: '📭 В этом разделе пока нет документов.',
    docPaidMsg: (name: string, price: number, card: string, cardOwner: string) =>
      `💰 <b>${name}</b> — платный документ.\n\nЦена: <b>${price.toLocaleString()} сум</b>\n\n📲 Для оплаты:\n👤 ${cardOwner}\n💳 ${card}\n\nОплатите и отправьте скриншот.`,
    docPaymentReceived: '✅ Оплата получена! Документ готовится...',
    adminWelcome: '💬 <b>Связаться с нами</b>\n\nНапишите ваше сообщение, мы ответим вам в ближайшее время:',
    adminSent: '✅ Ваше сообщение отправлено администратору. Скоро ответим!',
    adminMsgSend: '📨 Отправить сообщение',
    legalConsultWelcome: `⚖️ <b>Юридическое разъяснение</b>\n\nНаши юристы проанализируют вашу проблему и дадут понятное объяснение.\n\n💡 Услуга может быть <b>платной или бесплатной</b> в зависимости от объёма.\n\nОпишите вашу проблему подробно:`,
    legalConsultSent: '✅ Ваша заявка принята! Юристы рассмотрят и ответят в ближайшее время.',
    legalConsultWaiting: '⏳ Ваша заявка рассматривается, ожидайте...',
    docCreateWelcome: `✍️ <b>Составить документ</b>\n\nНаши юристы составят нужный юридический документ для вас.\n\n💡 Услуга может быть <b>платной или бесплатной</b> в зависимости от объёма.\n\nНапишите, какой документ вам нужен (например: трудовой договор, договор аренды, исковое заявление...):`,
    docCreateSent: '✅ Ваш запрос принят! Юристы рассмотрят и ответят в ближайшее время.',
    supportWelcome: '📞 <b>Поддержка</b>\n\nОпишите ваш вопрос или проблему:',
    supportSent: '✅ Ваше сообщение отправлено в службу поддержки!',
    requestAccepted: (account: string, comment: string) =>
      `✅ <b>Ваша заявка принята!</b>\n\n💬 Комментарий: ${comment}\n\n👤 Специалист: ${account}\n\nСвяжитесь с этим аккаунтом.`,
    requestRejected: (reason: string) =>
      `❌ <b>К сожалению, ваша заявка отклонена.</b>\n\n📝 Причина: ${reason}\n\nПриносим извинения. Если есть другие вопросы, обращайтесь снова.`,
    cancel: '❌ Отменено. Вы вернулись в главное меню.',
    adminPanel: '👨‍💼 <b>Панель администратора</b>\n\nВыберите раздел:',
    btnAdminMonitor: '📊 Мониторинг',
    btnAdminBroadcast: '📢 Массовая рассылка',
    btnAdminAddDoc: '📄 Добавить документ',
    btnAdminPayment: '💳 Платёжная карта',
    adminBroadcastPrompt: '📢 Введите сообщение для всех пользователей:',
    adminBroadcastDone: (count: number) => `✅ Сообщение отправлено ${count} пользователям.`,
    adminAddDocType: '📂 Выберите тип документа:',
    btnSampleDoc: '📄 Образец документа',
    btnTemplateDoc: '📋 Шаблон',
    adminAddDocCategory: '📂 Выберите категорию:',
    adminAddDocFile: '📎 Отправьте документ (файл или изображение):',
    adminAddDocName: '✏️ Дайте название документу (на узбекском):',
    adminAddDocNameRu: '✏️ Введите название на русском:',
    adminAddDocNameEn: '✏️ Введите название на английском:',
    adminAddDocCode: '🔑 Введите код документа (2 заглавные буквы + 3 цифры, например: HA001):',
    adminAddDocPrice: '💰 Укажите цену (0 = бесплатно, другое число = платно, в сумах):',
    adminDocAdded: '✅ Документ успешно добавлен!',
    adminPaymentMenu: '💳 Управление платёжными картами:',
    btnAddCard: '➕ Добавить карту',
    btnRemoveCard: '🗑️ Удалить карту',
    btnViewCards: '👁️ Список карт',
    adminCardOwner: '👤 Введите имя владельца карты:',
    adminCardNumber: '💳 Введите номер карты или ссылку:',
    adminCardAdded: '✅ Карта успешно добавлена!',
    adminCardRemoved: '✅ Карта удалена.',
    noCards: '💳 Карты ещё не добавлены.',
    monitoringInfo: (users: number, today: number, ads: number) =>
      `📊 <b>Мониторинг</b>\n\n👥 Всего пользователей: ${users}\n📅 Добавлено сегодня: ${today}\n📢 Всего объявлений: ${ads}`,
  },

  en: {
    welcome: '👋 Welcome to <b>LegalUZ</b>!\n\n⚖️ Professional legal platform connecting lawyers and clients in Uzbekistan.',
    selectLanguage: '🌐 Select language:',
    subscribeRequired: `📢 To use the bot, subscribe to these channels:\n\n1️⃣ @LegalUz_Y_u\n2️⃣ @LegalUz_M_u\n3️⃣ @Yurist_ND\n\n📁 Folder: https://t.me/addlist/LAV6HuGmEOJlOGVi`,
    checkSubscription: '✅ Check subscription',
    notSubscribed: '❌ You haven\'t subscribed to all channels yet!\n\nPlease subscribe and check again.',
    subscribed: '✅ Subscription confirmed! Welcome!',
    selectSection: '📋 Select a section:',
    btnAds: '📢 Post an ad',
    btnAI: '🤖 AI Consultation',
    btnDocs: '📁 Documents',
    btnAdmin: '💬 Contact us',
    btnLegalConsult: '⚖️ Legal explanation',
    btnDocCreate: '✍️ Document drafting',
    btnSupport: '📞 Support',
    btnBack: '🏠 Main menu',
    btnCancel: '❌ Cancel',
    btnMainMenu: '🏠 Main menu',
    selectAdType: '📢 Select ad type:',
    btnClientAd: '👤 As a client',
    btnSpecialistAd: '👨‍⚖️ As a specialist',
    clientAdField: '📌 What legal area do you need help with?\n\n(e.g. labor law, property, family, business...)',
    clientAdRegion: '📍 What region/city are you from?',
    clientAdDescription: '📝 Describe your issue in detail:',
    clientAdContact: '📞 Enter your contact info (phone or Telegram username):',
    clientAdPosted: '✅ Your ad has been posted successfully!\n\nSpecialists will contact you.',
    specialistAdField: '⚖️ What area do you specialize in?\n\n(e.g. criminal, civil, labor, family, business law...)',
    specialistAdRegion: '📍 What region/city do you work in?',
    specialistAdExperience: '📅 How many years of experience?',
    specialistAdPrice: '💰 Consultation fee (in soums or "Negotiable"):',
    specialistAdDescription: '📝 Brief information about yourself:',
    specialistAdContact: '📞 Enter your contact info (phone or Telegram username):',
    specialistAdPosted: '✅ Your ad has been posted successfully!',
    aiWelcome: '🤖 <b>AI Consultation</b>\n\nAsk a question about Uzbekistan law. The legal assistant will help you.\n\n❓ Enter your question:',
    aiTyping: '⏳ Preparing answer...',
    aiError: '❌ An error occurred. Please try again.',
    docsWelcome: '📁 <b>Documents</b>\n\nSelect a section:',
    btnDocSamples: '📄 Document samples',
    btnDocTemplates: '📋 Templates',
    docSampleCategories: '📄 Select sample category:',
    btnSudHujjatlari: '⚖️ Court documents',
    btnArizalar: '📝 Applications',
    btnShartnomaMisollari: '📃 Contract samples',
    btnBoshqaHujjatlar: '📂 Other documents',
    templateCategories: '📋 Select template category:',
    btnShartnomalar: '📑 Contracts',
    btnDavoArizalari: '⚖️ Claims',
    btnKorporativHujjatlar: '🏢 Corporate documents',
    btnTemplateBoshqa: '📂 Other templates',
    docsEmpty: '📭 No documents available in this section yet.',
    docPaidMsg: (name: string, price: number, card: string, cardOwner: string) =>
      `💰 <b>${name}</b> is a paid document.\n\nPrice: <b>${price.toLocaleString()} soums</b>\n\n📲 Payment details:\n👤 ${cardOwner}\n💳 ${card}\n\nPay and send a screenshot.`,
    docPaymentReceived: '✅ Payment received! Document is being prepared...',
    adminWelcome: '💬 <b>Contact us</b>\n\nWrite your message, we\'ll respond shortly:',
    adminSent: '✅ Your message has been sent to the admin. We\'ll reply soon!',
    adminMsgSend: '📨 Send message',
    legalConsultWelcome: `⚖️ <b>Legal Explanation</b>\n\nOur lawyers will analyze your legal problem and provide a clear explanation.\n\n💡 The service may be <b>paid or free</b> depending on the scope.\n\nDescribe your problem in detail:`,
    legalConsultSent: '✅ Your request has been accepted! Lawyers will review and respond shortly.',
    legalConsultWaiting: '⏳ Your request is being reviewed, please wait...',
    docCreateWelcome: `✍️ <b>Document Drafting</b>\n\nOur lawyers will draft the required legal document for you.\n\n💡 The service may be <b>paid or free</b> depending on the scope.\n\nDescribe what document you need (e.g. employment contract, lease agreement, claim...):`,
    docCreateSent: '✅ Your request has been accepted! Lawyers will review and respond shortly.',
    supportWelcome: '📞 <b>Support</b>\n\nDescribe your question or issue:',
    supportSent: '✅ Your message has been sent to support!',
    requestAccepted: (account: string, comment: string) =>
      `✅ <b>Your request has been accepted!</b>\n\n💬 Comment: ${comment}\n\n👤 Specialist: ${account}\n\nContact this account.`,
    requestRejected: (reason: string) =>
      `❌ <b>Unfortunately, your request was rejected.</b>\n\n📝 Reason: ${reason}\n\nWe apologize. Feel free to contact us again.`,
    cancel: '❌ Cancelled. Returned to main menu.',
    adminPanel: '👨‍💼 <b>Admin Panel</b>\n\nSelect a section:',
    btnAdminMonitor: '📊 Monitoring',
    btnAdminBroadcast: '📢 Broadcast',
    btnAdminAddDoc: '📄 Add document',
    btnAdminPayment: '💳 Payment card',
    adminBroadcastPrompt: '📢 Enter the message to send to all users:',
    adminBroadcastDone: (count: number) => `✅ Message sent to ${count} users.`,
    adminAddDocType: '📂 Select document type:',
    btnSampleDoc: '📄 Document sample',
    btnTemplateDoc: '📋 Template',
    adminAddDocCategory: '📂 Select category:',
    adminAddDocFile: '📎 Send the document (file or image):',
    adminAddDocName: '✏️ Give the document a name (in Uzbek):',
    adminAddDocNameRu: '✏️ Enter the document name in Russian:',
    adminAddDocNameEn: '✏️ Enter the document name in English:',
    adminAddDocCode: '🔑 Enter document code (2 uppercase letters + 3 digits, e.g. HA001):',
    adminAddDocPrice: '💰 Set price (0 = free, other = paid, in soums):',
    adminDocAdded: '✅ Document added successfully!',
    adminPaymentMenu: '💳 Payment card management:',
    btnAddCard: '➕ Add card',
    btnRemoveCard: '🗑️ Remove card',
    btnViewCards: '👁️ View cards',
    adminCardOwner: '👤 Enter card owner\'s name:',
    adminCardNumber: '💳 Enter card number or link:',
    adminCardAdded: '✅ Card added successfully!',
    adminCardRemoved: '✅ Card removed.',
    noCards: '💳 No cards added yet.',
    monitoringInfo: (users: number, today: number, ads: number) =>
      `📊 <b>Monitoring</b>\n\n👥 Total users: ${users}\n📅 Added today: ${today}\n📢 Total ads: ${ads}`,
  },
} as const;

export type Texts = typeof languages.uz;

export function t(lang: Lang): Texts {
  return languages[lang] ?? languages.uz;
}
